# Updates are grouped together by ecosystem in a single PR. An update can be
# removed from a combined update PR via comments to dependabot:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#managing-dependabot-pull-requests-for-grouped-updates-with-comment-commands

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["skip-notes"]
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - "*"
